<?php
/*
Author:			This code was generated by DALGen version 1.1.0.0 available at https://github.com/H0r53/DALGen 
Date:			6/24/2018
Description:	Creates the DAL class for  Song table and respective stored procedures

*/



class Song {

	// This is for local purposes only! In hosted environments the db_settings.php file should be outside of the webroot, such as: include("/outside-webroot/db_settings.php");
	protected static function getDbSettings() { return "DAL/db_localsettings.php"; }

	/******************************************************************/
	// Properties
	/******************************************************************/

	protected $id;
	protected $name;
	protected $description;
	protected $createdByUserId;
	protected $imgUrl;
	protected $fileUrl;
	protected $createDate;


	/******************************************************************/
	// Constructors
	/******************************************************************/
	public function __construct() {
		$argv = func_get_args();
		switch( func_num_args() ) {
			case 0:
				self::__constructBase();
				break;
			case 1:
				self::__constructPK( $argv[0] );
				break;
			case 7:
				self::__constructFull( $argv[0], $argv[1], $argv[2], $argv[3], $argv[4], $argv[5], $argv[6] );
		}
	}


	public function __constructBase() {
		$this->id = 0;
		$this->name = "";
		$this->description = "";
		$this->createdByUserId = 0;
		$this->imgUrl = "";
		$this->fileUrl = "";
		$this->createDate = "";
	}


	public function __constructPK($paramId) {
		$this->load($paramId);
	}


	public function __constructFull($paramId,$paramName,$paramDescription,$paramCreatedByUserId,$paramImgUrl,$paramFileUrl,$paramCreateDate) {
		$this->id = $paramId;
		$this->name = $paramName;
		$this->description = $paramDescription;
		$this->createdByUserId = $paramCreatedByUserId;
		$this->imgUrl = $paramImgUrl;
		$this->fileUrl = $paramFileUrl;
		$this->createDate = $paramCreateDate;
	}


	/******************************************************************/
	// Accessors / Mutators
	/******************************************************************/

	public function getId(){
		return $this->id;
	}
	public function setId($value){
		$this->id = $value;
	}
	public function getName(){
		return $this->name;
	}
	public function setName($value){
		$this->name = $value;
	}
	public function getDescription(){
		return $this->description;
	}
	public function setDescription($value){
		$this->description = $value;
	}
	public function getCreatedByUserId(){
		return $this->createdByUserId;
	}
	public function setCreatedByUserId($value){
		$this->createdByUserId = $value;
	}
	public function getImgUrl(){
		return $this->imgUrl;
	}
	public function setImgUrl($value){
		$this->imgUrl = $value;
	}
	public function getFileUrl(){
		return $this->fileUrl;
	}
	public function setFileUrl($value){
		$this->fileUrl = $value;
	}
	public function getCreateDate(){
		return $this->createDate;
	}
	public function setCreateDate($value){
		$this->createDate = $value;
	}


	/******************************************************************/
	// Public Methods
	/******************************************************************/


	public function load($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_Song_Load(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);

		while ($row = $result->fetch_assoc()) {
		 $this->setId($row['id']);
		 $this->setName($row['name']);
		 $this->setDescription($row['description']);
		 $this->setCreatedByUserId($row['createdByUserId']);
		 $this->setImgUrl($row['imgUrl']);
		 $this->setFileUrl($row['fileUrl']);
		 $this->setCreateDate($row['createDate']);
		}
	}


	public function save() {
		if ($this->getId() == 0)
			$this->insert();
		else
			$this->update();
	}

	/******************************************************************/
	// Private Methods
	/******************************************************************/



	private function insert() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_Song_Add(?,?,?,?,?,?)');
		$arg1 = $this->getName();
		$arg2 = $this->getDescription();
		$arg3 = $this->getCreatedByUserId();
		$arg4 = $this->getImgUrl();
		$arg5 = $this->getFileUrl();
		$arg6 = $this->getCreateDate();
		$stmt->bind_param('ssisss',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		while ($row = $result->fetch_assoc()) {
			// By default, the DALGen generated INSERT procedure returns the scope identity as id
			$this->load($row['id']);
		}
	}


	private function update() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_Song_Update(?,?,?,?,?,?,?)');
		$arg1 = $this->getId();
		$arg2 = $this->getName();
		$arg3 = $this->getDescription();
		$arg4 = $this->getCreatedByUserId();
		$arg5 = $this->getImgUrl();
		$arg6 = $this->getFileUrl();
		$arg7 = $this->getCreateDate();
		$stmt->bind_param('ississs',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6,$arg7);
		$stmt->execute();
	}

	private static function setNullValue($value){
		if ($value == "")
			return null;
		else
			return $value;
	}

	/******************************************************************/
	// Static Methods
	/******************************************************************/



	public static function loadall() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_Song_LoadAll()');
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$song = new Song($row['id'],$row['name'],$row['description'],$row['createdByUserId'],$row['imgUrl'],$row['fileUrl'],$row['createDate']);
				$arr[] = $song;
			}
			return $arr;
		}
		else {
			return array();
		}
	}


	public static function remove($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_Song_Delete(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();
	}


	public static function search($paramId,$paramName,$paramDescription,$paramCreatedByUserId,$paramImgUrl,$paramFileUrl,$paramCreateDate) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_Song_Search(?,?,?,?,?,?,?)');
		$arg1 = Song::setNullValue($paramId);
		$arg2 = Song::setNullValue($paramName);
		$arg3 = Song::setNullValue($paramDescription);
		$arg4 = Song::setNullValue($paramCreatedByUserId);
		$arg5 = Song::setNullValue($paramImgUrl);
		$arg6 = Song::setNullValue($paramFileUrl);
		$arg7 = Song::setNullValue($paramCreateDate);
		$stmt->bind_param('ississs',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6,$arg7);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$song = new Song($row['id'],$row['name'],$row['description'],$row['createdByUserId'],$row['imgUrl'],$row['fileUrl'],$row['createDate']);
				$arr[] = $song;
			}
			return $arr;
		}
		else {
			return array();
		}
	}
}
