<?php
/*
Author:			This code was generated by DALGen version 1.1.0.0 available at https://github.com/H0r53/DALGen 
Date:			3/5/2018
Description:	Creates the DAL class for  User table and respective stored procedures

*/



class User {

	// This is for local purposes only! In hosted environments the db_settings.php file should be outside of the webroot, such as: include("/outside-webroot/db_settings.php");
	protected static function getDbSettings() { return "DAL/db_localsettings.php"; }

	/******************************************************************/
	// Properties
	/******************************************************************/

	protected $id;
	protected $username;
	protected $password;
	protected $email;
	protected $imgUrl;
	protected $roleId;


	/******************************************************************/
	// Constructors
	/******************************************************************/
	public function __construct() {
		$argv = func_get_args();
		switch( func_num_args() ) {
			case 0:
				self::__constructBase();
				break;
			case 1:
				self::__constructPK( $argv[0] );
				break;
			case 6:
				self::__constructFull( $argv[0], $argv[1], $argv[2], $argv[3], $argv[4], $argv[5] );
		}
	}


	public function __constructBase() {
		$this->id = 0;
		$this->username = "";
		$this->password = "";
		$this->email = "";
		$this->imgUrl = "";
		$this->roleId = 0;
	}


	public function __constructPK($paramId) {
		$this->load($paramId);
	}


	public function __constructFull($paramId,$paramUsername,$paramPassword,$paramEmail,$paramImgUrl,$paramRoleId) {
		$this->id = $paramId;
		$this->username = $paramUsername;
		$this->password = $paramPassword;
		$this->email = $paramEmail;
		$this->imgUrl = $paramImgUrl;
		$this->roleId = $paramRoleId;
	}


	/******************************************************************/
	// Accessors / Mutators
	/******************************************************************/

	public function getId(){
		return $this->id;
	}
	public function setId($value){
		$this->id = $value;
	}
	public function getUsername(){
		return $this->username;
	}
	public function setUsername($value){
		$this->username = $value;
	}
	public function getPassword(){
		return $this->password;
	}
	public function setPassword($value){
		$this->password = $value;
	}
	public function getEmail(){
		return $this->email;
	}
	public function setEmail($value){
		$this->email = $value;
	}
	public function getImgUrl(){
		return $this->imgUrl;
	}
	public function setImgUrl($value){
		$this->imgUrl = $value;
	}
	public function getRoleId(){
		return $this->roleId;
	}
	public function setRoleId($value){
		$this->roleId = $value;
	}


	/******************************************************************/
	// Public Methods
	/******************************************************************/


	public function load($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_User_Load(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);

		while ($row = $result->fetch_assoc()) {
		 $this->setId($row['id']);
		 $this->setUsername($row['username']);
		 $this->setPassword($row['password']);
		 $this->setEmail($row['email']);
		 $this->setImgUrl($row['imgUrl']);
		 $this->setRoleId($row['roleId']);
		}
	}


	public function save() {
		if ($this->getId() == 0)
			$this->insert();
		else
			$this->update();
	}

	/******************************************************************/
	// Private Methods
	/******************************************************************/



	private function insert() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_User_Add(?,?,?,?,?)');
		$arg1 = $this->getUsername();
		$arg2 = $this->getPassword();
		$arg3 = $this->getEmail();
		$arg4 = $this->getImgUrl();
		$arg5 = $this->getRoleId();
		$stmt->bind_param('ssssi',$arg1,$arg2,$arg3,$arg4,$arg5);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		while ($row = $result->fetch_assoc()) {
			// By default, the DALGen generated INSERT procedure returns the scope identity as id
			$this->load($row['id']);
		}
	}


	private function update() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_User_Update(?,?,?,?,?,?)');
		$arg1 = $this->getId();
		$arg2 = $this->getUsername();
		$arg3 = $this->getPassword();
		$arg4 = $this->getEmail();
		$arg5 = $this->getImgUrl();
		$arg6 = $this->getRoleId();
		$stmt->bind_param('issssi',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6);
		$stmt->execute();
	}

	private static function setNullValue($value){
		if ($value == "")
			return null;
		else
			return $value;
	}

	/******************************************************************/
	// Static Methods
	/******************************************************************/



	public static function loadall() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_User_LoadAll()');
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$user = new User($row['id'],$row['username'],$row['password'],$row['email'],$row['imgUrl'],$row['roleId']);
				$arr[] = $user;
			}
			return $arr;
		}
		else {
			die("The query yielded zero results.No rows found.");
		}
	}


	public static function remove($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_User_Remove(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();
	}


	public static function search($paramId,$paramUsername,$paramPassword,$paramEmail,$paramImgUrl,$paramRoleId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_User_Search(?,?,?,?,?,?)');
		$arg1 = User::setNullValue($paramId);
		$arg2 = User::setNullValue($paramUsername);
		$arg3 = User::setNullValue($paramPassword);
		$arg4 = User::setNullValue($paramEmail);
		$arg5 = User::setNullValue($paramImgUrl);
		$arg6 = User::setNullValue($paramRoleId);
		$stmt->bind_param('issssi',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$user = new User($row['id'],$row['username'],$row['password'],$row['email'],$row['imgUrl'],$row['roleId']);
				$arr[] = $user;
			}
			return $arr;
		}
		else {
			die("The query yielded zero results.No rows found.");
		}
	}
}
