/*
Author:			This code was generated by DALGen version 1.1.0.0 available at https://github.com/H0r53/DALGen 
Date:			4/24/2018
Description:	Creates the FileCategory table and respective stored procedures

*/


USE tafers;



-- ------------------------------------------------------------
-- Drop existing objects
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `tafers`.`FileCategory`;
DROP PROCEDURE IF EXISTS `tafers`.`usp_FileCategory_Load`;
DROP PROCEDURE IF EXISTS `tafers`.`usp_FileCategory_LoadAll`;
DROP PROCEDURE IF EXISTS `tafers`.`usp_FileCategory_Add`;
DROP PROCEDURE IF EXISTS `tafers`.`usp_FileCategory_Update`;
DROP PROCEDURE IF EXISTS `tafers`.`usp_FileCategory_Delete`;
DROP PROCEDURE IF EXISTS `tafers`.`usp_FileCategory_Search`;


-- ------------------------------------------------------------
-- Create table
-- ------------------------------------------------------------



CREATE TABLE `tafers`.`FileCategory` (
id INT AUTO_INCREMENT,
name VARCHAR(255),
description VARCHAR(512),
CONSTRAINT pk_FileCategory_id PRIMARY KEY (id)
);


-- ------------------------------------------------------------
-- Create default SCRUD sprocs for this table
-- ------------------------------------------------------------


DELIMITER //
CREATE PROCEDURE `tafers`.`usp_FileCategory_Load`
(
	 IN paramid INT
)
BEGIN
	SELECT
		`FileCategory`.`id` AS `id`,
		`FileCategory`.`name` AS `name`,
		`FileCategory`.`description` AS `description`
	FROM `FileCategory`
	WHERE 		`FileCategory`.`id` = paramid;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `tafers`.`usp_FileCategory_LoadAll`
()
BEGIN
	SELECT
		`FileCategory`.`id` AS `id`,
		`FileCategory`.`name` AS `name`,
		`FileCategory`.`description` AS `description`
	FROM `FileCategory`;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `tafers`.`usp_FileCategory_Add`
(
	 IN paramname VARCHAR(255),
	 IN paramdescription VARCHAR(512)
)
BEGIN
	INSERT INTO `FileCategory` (name,description)
	VALUES (paramname, paramdescription);
	-- Return last inserted ID as result
	SELECT LAST_INSERT_ID() as id;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `tafers`.`usp_FileCategory_Update`
(
	IN paramid INT,
	IN paramname VARCHAR(255),
	IN paramdescription VARCHAR(512)
)
BEGIN
	UPDATE `FileCategory`
	SET name = paramname
		,description = paramdescription
	WHERE		`FileCategory`.`id` = paramid;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `tafers`.`usp_FileCategory_Delete`
(
	IN paramid INT
)
BEGIN
	DELETE FROM `FileCategory`
	WHERE		`FileCategory`.`id` = paramid;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `tafers`.`usp_FileCategory_Search`
(
	IN paramid INT,
	IN paramname VARCHAR(255),
	IN paramdescription VARCHAR(512)
)
BEGIN
	SELECT
		`FileCategory`.`id` AS `id`,
		`FileCategory`.`name` AS `name`,
		`FileCategory`.`description` AS `description`
	FROM `FileCategory`
	WHERE
		COALESCE(FileCategory.`id`,0) = COALESCE(paramid,FileCategory.`id`,0)
		AND COALESCE(FileCategory.`name`,'') = COALESCE(paramname,FileCategory.`name`,'')
		AND COALESCE(FileCategory.`description`,'') = COALESCE(paramdescription,FileCategory.`description`,'');
END //
DELIMITER ;


